### ISSUE TITLE
stripping transparency from PNGs

### ISSUE THREAD

**Issue by meatpaste** [meatpaste/imgsizer#2]
it looks like the plugin is stripping transparency from PNGs, (they now have a black background). Is there a way to prevent this?

**Comment by paulcripps** [comment]
![logo-ip-2x](https://cloud.githubusercontent.com/assets/1560544/16980418/b64043a0-4e5d-11e6-80b8-3d1ce3d8f37f.png)

Here's an example logo. Once image sizer has sized the image the end result has a black background: 

![122--65-logo-ip-2x](https://cloud.githubusercontent.com/assets/1560544/16980473/0e4b4dd8-4e5e-11e6-9427-93f99cc13fe1.png)

![screen shot 2016-07-20 at 09 36 50](https://cloud.githubusercontent.com/assets/1560544/16980425/c222b64e-4e5d-11e6-8051-92ae7e1f413d.png)

:)

**Comment by MobsterGit** [comment]
Same problem here.  Any suggestions?

**Comment by paulcripps** [comment]
@MobsterGit I'm afraid not, I ended up reverting to the older imgsizer for ee3 thats unsupported :/

**Comment by meatpaste** [comment]
Resolved in 4.0.2
