### ISSUE TITLE
Errors with source URL

### ISSUE THREAD

**Issue by paulcripps** [meatpaste/imgsizer#3]
It's been a long day, but I've noticed this odd issue, could be my bad, not sure!

To help isolate the issue I've added it to a stripped back template that ONLY contains the following:

```
{exp:channel:entries channel="awards" status="open|draft" disable="categories|category_fields|member_data|pagination"}

    {press_awards_thumbnail}
    <!-- outputs : http://localdomain.dev/images/uploads/press-and-awards/img-03-2x.jpg -->

    {exp:imgsizer:size src="{press_awards_thumbnail}" width="100"}{sized}{/exp:imgsizer:size}
    <!-- does not work -->

<!-- where as these both work -->

    {exp:imgsizer:size src="/images/uploads/press-and-awards/img-03-2x.jpg" width="100"}{sized}{/exp:imgsizer:size}

    {exp:imgsizer:placeholder size_src="/images/uploads/press-and-awards/img-03-2x.jpg" width="100"}{/exp:imgsizer:placeholder} 

{/exp:channel:entries}
```

In the example about, my field {press_awards_thumbnail} is a default file filed. As you can see outputs the full local domain:

`http://localdomain.dev/images/uploads/press-and-awards/img-03-2x.jpg`

If we use this field {press_awards_thumbnail} as the param for imgsizer nothing works.

If I manually edit and hadrcode:

`/images/uploads/press-and-awards/img-03-2x.jpg`

It works fine.

In the template debug I can see the following:

```
Calling Tag: {exp:imgsizer:size src="http://localdomain.dev/images/uploads/press-and-awards/img-03-2x.jpg" width="100"}

ImageSizer Error: Can't read size source file.
```

Oddly, viewing the full URL as a URL in my browser I can see the test image: 

`http://localdomain.dev/images/uploads/press-and-awards/img-03-2x.jpg`

**Comment by meatpaste** [comment]
This version no longer captures remote images, and doing so to images on your own site is an overhead you don't need. You should instead amend the upload directory URL so that it begins with a '/'.
